[package]
name = "grapher"
version = "0.1.0"
edition = "2021"

[features]
default = ["desktop"]
desktop = ["dep:tauri", "dep:tauri-build"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
rusqlite = { version = "0.32", features = ["bundled"] }
libc = "0.2"
tauri = { version = "2", optional = true , features = [] }

[build-dependencies]
tauri-build = { version = "2", optional = true , features = [] }

[dev-dependencies]
tempfile = "3"
